//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First_Approach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerenceEntities : DbContext
    {
        public EcommerenceEntities()
            : base("name=EcommerenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department_table> Department_table { get; set; }
        public virtual DbSet<Dropdown> Dropdowns { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Product_data> Product_data { get; set; }
        public virtual DbSet<Sign_Up> Sign_Up { get; set; }
        public virtual DbSet<Student_table> Student_table { get; set; }
    }
}
