//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First_Approach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> P_Price { get; set; }
        public string P_Description { get; set; }
        public string P_Image { get; set; }
        public Nullable<int> C_Id { get; set; }
    
        public virtual Product_Category Product_Category { get; set; }
    }
}
