//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First_Approach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_data
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public Nullable<decimal> P_Price { get; set; }
        public string P_Image { get; set; }
    }
}
